name: Rust

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Get Rust Musl
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
